target-version = "py311"

select = ["F", "W", "I", "D", "UP", "ANN", "TCH", "TD", "FIX", "ICN", "PT"]
ignore = ["D100", "ANN101"]

[lint.pydocstyle]
convention = "google"

[lint.pycodestyle]
max-doc-length = 120

[isort]
known-third-party = ["wandb"]