name: ci
on: [ push, pull_request ]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.1.4
      - uses: codespell-project/actions-codespell@v2
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install --no-deps tensorflow-text==2.14.0 && pip install -r requirements.txt

      - name: Run Tests
        run: python -m pytest